# Generated by Django 5.0.6 on 2024-07-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_receipe_receipe_view_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
