# Generated by Django 5.0.6 on 2024-07-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_receipe_receipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='receipe_category',
            field=models.CharField(choices=[('starters', 'Starters'), ('main_course', 'Main Course'), ('desserts', 'Desserts')], max_length=20),
        ),
    ]
